using Solucionesetech.DataAccess.Models;
using Solucionesetech.DataAccess.Repositories;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Text;

namespace Solucionesetech.DataAccess
{
    public class UnitOfWork : IDisposable
    {

        #region Fields
        private readonly DbContextOptions<TRAVELSContext> _options;
        private OriginRepository _originRepository;
        private DestinationRepository _destinationRepository;
        private AvailableTravelRepository _availableTravelRepository;
        private TravelRepository _travelRepository;
        private TravelerRepository _TravelerRepository;
        private SelectorRepository _selectorRepository;

        #endregion

        #region Constructors
        public UnitOfWork(string nameOrConnectionString)
        {
            this._options = new DbContextOptionsBuilder<TRAVELSContext>()
                   .UseSqlServer(nameOrConnectionString)
                   //.UseLoggerFactory(loggerFactory) //Optional, this logs SQL generated by EF Core to the Console
                   .Options;
        }


        #endregion

        #region IUnitOfWork Members
      
        public OriginRepository OriginRepository
        {
            get { return _originRepository ?? (_originRepository = new OriginRepository(_options)); }
        }
        public DestinationRepository DestinationRepository
        {
            get { return _destinationRepository ?? (_destinationRepository = new DestinationRepository(_options)); }
        }
        public AvailableTravelRepository AvailableTravelRepository
        {
            get { return _availableTravelRepository ?? (_availableTravelRepository = new AvailableTravelRepository(_options)); }
        }
        public TravelRepository TravelRepository
        {
            get { return _travelRepository ?? (_travelRepository = new TravelRepository(_options)); }
        }
        public TravelerRepository TravelerRepository
        {
            get { return _TravelerRepository ?? (_TravelerRepository = new TravelerRepository(_options)); }
        }
        public SelectorRepository SelectorRepository
        {
            get { return _selectorRepository ?? (_selectorRepository = new SelectorRepository(_options)); }
        }
       
        #endregion

        #region IDisposable Members
        public void Dispose()
        {
            this._originRepository = null;
            this._destinationRepository = null;
            this._availableTravelRepository = null;
            this._travelRepository = null;
            this._TravelerRepository = null;
            this._selectorRepository = null;
           
            // _options.Dispose();
        }
        #endregion
    }
}
